// <auto-generated />
using System;
using Amazon_clone.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20260223214748_AddProductPropertyField")]
    partial class AddProductPropertyField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lifestyle"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Home"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Auto"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Health"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Clothing",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Shoes",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Computers / Laptops / Tablets",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "Mobile Phones",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "Audio and Wearables",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 11,
                            Name = "Cameras / Photo Equipment",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 12,
                            Name = "Gaming",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 13,
                            Name = "Home Decor",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 14,
                            Name = "Furniture",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 15,
                            Name = "Lighting",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 16,
                            Name = "Yard and Garden",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 17,
                            Name = "Tools / Hardware / Plumbing",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 18,
                            Name = "Building Materials",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 19,
                            Name = "Sports / Outdoor / Fitness",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 20,
                            Name = "Auto Parts / Accessories",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 21,
                            Name = "Toys Kids",
                            ParentCategoryId = 5
                        },
                        new
                        {
                            Id = 22,
                            Name = "Books / Media",
                            ParentCategoryId = 5
                        },
                        new
                        {
                            Id = 23,
                            Name = "Health",
                            ParentCategoryId = 5
                        });
                });

            modelBuilder.Entity("CategoryProperty", b =>
                {
                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyDefinitionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVariantOption")
                        .HasColumnType("bit");

                    b.HasKey("CategoryId", "PropertyDefinitionId");

                    b.HasIndex("PropertyDefinitionId");

                    b.ToTable("CategoryProperty");

                    b.HasData(
                        new
                        {
                            CategoryId = 6,
                            PropertyDefinitionId = 1,
                            IsRequired = true,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 6,
                            PropertyDefinitionId = 2,
                            IsRequired = false,
                            IsVariantOption = true
                        },
                        new
                        {
                            CategoryId = 6,
                            PropertyDefinitionId = 3,
                            IsRequired = false,
                            IsVariantOption = true
                        },
                        new
                        {
                            CategoryId = 7,
                            PropertyDefinitionId = 1,
                            IsRequired = true,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 7,
                            PropertyDefinitionId = 2,
                            IsRequired = false,
                            IsVariantOption = true
                        },
                        new
                        {
                            CategoryId = 7,
                            PropertyDefinitionId = 3,
                            IsRequired = false,
                            IsVariantOption = true
                        },
                        new
                        {
                            CategoryId = 7,
                            PropertyDefinitionId = 4,
                            IsRequired = false,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 7,
                            PropertyDefinitionId = 5,
                            IsRequired = false,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 7,
                            PropertyDefinitionId = 6,
                            IsRequired = false,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 7,
                            PropertyDefinitionId = 7,
                            IsRequired = false,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 7,
                            PropertyDefinitionId = 8,
                            IsRequired = false,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 7,
                            PropertyDefinitionId = 9,
                            IsRequired = false,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 7,
                            PropertyDefinitionId = 10,
                            IsRequired = false,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 7,
                            PropertyDefinitionId = 11,
                            IsRequired = false,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 7,
                            PropertyDefinitionId = 12,
                            IsRequired = false,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 7,
                            PropertyDefinitionId = 13,
                            IsRequired = false,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 7,
                            PropertyDefinitionId = 14,
                            IsRequired = false,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 7,
                            PropertyDefinitionId = 15,
                            IsRequired = false,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 7,
                            PropertyDefinitionId = 16,
                            IsRequired = false,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 7,
                            PropertyDefinitionId = 17,
                            IsRequired = false,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 8,
                            PropertyDefinitionId = 1,
                            IsRequired = true,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 9,
                            PropertyDefinitionId = 1,
                            IsRequired = true,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 10,
                            PropertyDefinitionId = 1,
                            IsRequired = true,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 11,
                            PropertyDefinitionId = 1,
                            IsRequired = true,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 12,
                            PropertyDefinitionId = 1,
                            IsRequired = true,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 13,
                            PropertyDefinitionId = 1,
                            IsRequired = true,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 14,
                            PropertyDefinitionId = 1,
                            IsRequired = true,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 15,
                            PropertyDefinitionId = 1,
                            IsRequired = true,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 16,
                            PropertyDefinitionId = 1,
                            IsRequired = true,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 17,
                            PropertyDefinitionId = 1,
                            IsRequired = true,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 18,
                            PropertyDefinitionId = 1,
                            IsRequired = true,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 19,
                            PropertyDefinitionId = 1,
                            IsRequired = true,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 20,
                            PropertyDefinitionId = 1,
                            IsRequired = true,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 21,
                            PropertyDefinitionId = 1,
                            IsRequired = true,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 22,
                            PropertyDefinitionId = 1,
                            IsRequired = true,
                            IsVariantOption = false
                        },
                        new
                        {
                            CategoryId = 23,
                            PropertyDefinitionId = 1,
                            IsRequired = true,
                            IsVariantOption = false
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("Data")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "IsPrimary");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("ProductProperty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PropertyDefinitionId");

                    b.ToTable("ProductProperty");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            PropertyDefinitionId = 1,
                            Value = "Generic Brand"
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 2,
                            PropertyDefinitionId = 1,
                            Value = "RunFast"
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 3,
                            PropertyDefinitionId = 1,
                            Value = "Apple"
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 4,
                            PropertyDefinitionId = 1,
                            Value = "Samsung"
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 5,
                            PropertyDefinitionId = 1,
                            Value = "Sony"
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 7,
                            PropertyDefinitionId = 1,
                            Value = "Sony"
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 22,
                            PropertyDefinitionId = 1,
                            Value = "Nike"
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 22,
                            PropertyDefinitionId = 4,
                            Value = "Dunk Low Retro"
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 22,
                            PropertyDefinitionId = 5,
                            Value = "DD1503-124"
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 22,
                            PropertyDefinitionId = 6,
                            Value = "Nike Sportswear"
                        },
                        new
                        {
                            Id = 11,
                            ProductId = 22,
                            PropertyDefinitionId = 7,
                            Value = "Leather upper with synthetic overlays"
                        },
                        new
                        {
                            Id = 12,
                            ProductId = 22,
                            PropertyDefinitionId = 8,
                            Value = "Soft textile lining"
                        },
                        new
                        {
                            Id = 13,
                            ProductId = 22,
                            PropertyDefinitionId = 9,
                            Value = "Cushioned foam insole"
                        },
                        new
                        {
                            Id = 14,
                            ProductId = 22,
                            PropertyDefinitionId = 10,
                            Value = "Lightweight EVA midsole"
                        },
                        new
                        {
                            Id = 15,
                            ProductId = 22,
                            PropertyDefinitionId = 11,
                            Value = "Durable rubber outsole with circular traction"
                        },
                        new
                        {
                            Id = 16,
                            ProductId = 22,
                            PropertyDefinitionId = 12,
                            Value = "Round"
                        },
                        new
                        {
                            Id = 17,
                            ProductId = 22,
                            PropertyDefinitionId = 13,
                            Value = "Vietnam"
                        },
                        new
                        {
                            Id = 18,
                            ProductId = 22,
                            PropertyDefinitionId = 14,
                            Value = "Lifestyle / Casual"
                        },
                        new
                        {
                            Id = 19,
                            ProductId = 22,
                            PropertyDefinitionId = 15,
                            Value = "All-season"
                        },
                        new
                        {
                            Id = 20,
                            ProductId = 22,
                            PropertyDefinitionId = 16,
                            Value = "Approx. 820 g per pair (EU 42)"
                        },
                        new
                        {
                            Id = 21,
                            ProductId = 22,
                            PropertyDefinitionId = 17,
                            Value = "3 cm"
                        });
                });

            modelBuilder.Entity("ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductId = 1,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 2,
                            ProductId = 1,
                            Quantity = 15
                        },
                        new
                        {
                            Id = 3,
                            ProductId = 2,
                            Quantity = 10
                        },
                        new
                        {
                            Id = 4,
                            ProductId = 2,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 5,
                            ProductId = 22,
                            Quantity = 12
                        },
                        new
                        {
                            Id = 6,
                            ProductId = 22,
                            Quantity = 14
                        },
                        new
                        {
                            Id = 7,
                            ProductId = 22,
                            Quantity = 11
                        },
                        new
                        {
                            Id = 8,
                            ProductId = 22,
                            Quantity = 9
                        },
                        new
                        {
                            Id = 9,
                            ProductId = 22,
                            Quantity = 8
                        },
                        new
                        {
                            Id = 10,
                            ProductId = 22,
                            Quantity = 7
                        });
                });

            modelBuilder.Entity("ProductVariantValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int>("PropertyDefinitionId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("PropertyDefinitionId");

                    b.ToTable("ProductVariantValue");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductVariantId = 1,
                            PropertyDefinitionId = 3,
                            Value = "M"
                        },
                        new
                        {
                            Id = 2,
                            ProductVariantId = 1,
                            PropertyDefinitionId = 2,
                            Value = "White"
                        },
                        new
                        {
                            Id = 3,
                            ProductVariantId = 2,
                            PropertyDefinitionId = 3,
                            Value = "L"
                        },
                        new
                        {
                            Id = 4,
                            ProductVariantId = 2,
                            PropertyDefinitionId = 2,
                            Value = "Black"
                        },
                        new
                        {
                            Id = 5,
                            ProductVariantId = 3,
                            PropertyDefinitionId = 3,
                            Value = "41"
                        },
                        new
                        {
                            Id = 6,
                            ProductVariantId = 3,
                            PropertyDefinitionId = 2,
                            Value = "White"
                        },
                        new
                        {
                            Id = 7,
                            ProductVariantId = 4,
                            PropertyDefinitionId = 3,
                            Value = "42"
                        },
                        new
                        {
                            Id = 8,
                            ProductVariantId = 4,
                            PropertyDefinitionId = 2,
                            Value = "Black"
                        },
                        new
                        {
                            Id = 9,
                            ProductVariantId = 5,
                            PropertyDefinitionId = 3,
                            Value = "41"
                        },
                        new
                        {
                            Id = 10,
                            ProductVariantId = 5,
                            PropertyDefinitionId = 2,
                            Value = "White"
                        },
                        new
                        {
                            Id = 11,
                            ProductVariantId = 6,
                            PropertyDefinitionId = 3,
                            Value = "42"
                        },
                        new
                        {
                            Id = 12,
                            ProductVariantId = 6,
                            PropertyDefinitionId = 2,
                            Value = "White"
                        },
                        new
                        {
                            Id = 13,
                            ProductVariantId = 7,
                            PropertyDefinitionId = 3,
                            Value = "43"
                        },
                        new
                        {
                            Id = 14,
                            ProductVariantId = 7,
                            PropertyDefinitionId = 2,
                            Value = "White"
                        },
                        new
                        {
                            Id = 15,
                            ProductVariantId = 8,
                            PropertyDefinitionId = 3,
                            Value = "41"
                        },
                        new
                        {
                            Id = 16,
                            ProductVariantId = 8,
                            PropertyDefinitionId = 2,
                            Value = "Brown"
                        },
                        new
                        {
                            Id = 17,
                            ProductVariantId = 9,
                            PropertyDefinitionId = 3,
                            Value = "42"
                        },
                        new
                        {
                            Id = 18,
                            ProductVariantId = 9,
                            PropertyDefinitionId = 2,
                            Value = "Brown"
                        },
                        new
                        {
                            Id = 19,
                            ProductVariantId = 10,
                            PropertyDefinitionId = 3,
                            Value = "43"
                        },
                        new
                        {
                            Id = 20,
                            ProductVariantId = 10,
                            PropertyDefinitionId = 2,
                            Value = "Brown"
                        });
                });

            modelBuilder.Entity("PropertyDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("PropertyDefinition");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataType = "Text",
                            GroupName = "General",
                            Name = "Brand"
                        },
                        new
                        {
                            Id = 2,
                            DataType = "Text",
                            GroupName = "Variant",
                            Name = "Color"
                        },
                        new
                        {
                            Id = 3,
                            DataType = "Text",
                            GroupName = "Variant",
                            Name = "Size"
                        },
                        new
                        {
                            Id = 4,
                            DataType = "Text",
                            GroupName = "General",
                            Name = "Model Name"
                        },
                        new
                        {
                            Id = 5,
                            DataType = "Text",
                            GroupName = "General",
                            Name = "Model Number"
                        },
                        new
                        {
                            Id = 6,
                            DataType = "Text",
                            GroupName = "General",
                            Name = "Collection"
                        },
                        new
                        {
                            Id = 7,
                            DataType = "Text",
                            GroupName = "Material",
                            Name = "Upper Material"
                        },
                        new
                        {
                            Id = 8,
                            DataType = "Text",
                            GroupName = "Material",
                            Name = "Lining"
                        },
                        new
                        {
                            Id = 9,
                            DataType = "Text",
                            GroupName = "Comfort",
                            Name = "Insole"
                        },
                        new
                        {
                            Id = 10,
                            DataType = "Text",
                            GroupName = "Comfort",
                            Name = "Midsole"
                        },
                        new
                        {
                            Id = 11,
                            DataType = "Text",
                            GroupName = "Material",
                            Name = "Outsole"
                        },
                        new
                        {
                            Id = 12,
                            DataType = "Text",
                            GroupName = "Fit",
                            Name = "Toe Shape"
                        },
                        new
                        {
                            Id = 13,
                            DataType = "Text",
                            GroupName = "General",
                            Name = "Country of Origin"
                        },
                        new
                        {
                            Id = 14,
                            DataType = "Text",
                            GroupName = "General",
                            Name = "Style"
                        },
                        new
                        {
                            Id = 15,
                            DataType = "Text",
                            GroupName = "General",
                            Name = "Season"
                        },
                        new
                        {
                            Id = 16,
                            DataType = "Text",
                            GroupName = "General",
                            Name = "Weight"
                        },
                        new
                        {
                            Id = 17,
                            DataType = "Text",
                            GroupName = "Fit",
                            Name = "Sole Height"
                        });
                });

            modelBuilder.Entity("Web_Api_Amazon.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 6,
                            Description = "Amazon Essentials men's short-sleeve crewneck t-shirt in soft jersey knit.",
                            ImageUrl = "/images/products/amazon_essentials_tshirt.png",
                            Name = "Amazon Essentials Men's Short-Sleeve Crewneck T-Shirt",
                            Price = 18.989999999999998
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 7,
                            Description = "adidas Grand Court 2.0 sneakers with a synthetic leather upper and rubber outsole.",
                            ImageUrl = "/images/products/adidas_grand_court.png",
                            Name = "adidas Men's Grand Court 2.0 Sneakers",
                            Price = 69.989999999999995
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 8,
                            Description = "Apple MacBook Air 13-inch laptop with M2 chip, 8GB RAM, and 256GB SSD storage.",
                            ImageUrl = "/images/products/macbook_air_m2.png",
                            Name = "Apple MacBook Air 13-inch Laptop (M2, 8GB, 256GB)",
                            Price = 1099.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 9,
                            Description = "Samsung Galaxy S24 unlocked smartphone with advanced camera system.",
                            ImageUrl = "/images/products/galaxy_s24.png",
                            Name = "Samsung Galaxy S24 Unlocked Smartphone",
                            Price = 799.99000000000001
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 10,
                            Description = "Sony WH-1000XM5 wireless noise canceling headphones with premium sound.",
                            ImageUrl = "/images/products/sony_wh1000xm5.png",
                            Name = "Sony WH-1000XM5 Wireless Noise Canceling Headphones",
                            Price = 398.0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 11,
                            Description = "Canon EOS R10 mirrorless camera kit with RF-S 18-45mm lens for versatile shooting.",
                            ImageUrl = "/images/products/canon_eos_r10.png",
                            Name = "Canon EOS R10 Mirrorless Camera with RF-S 18-45mm Lens",
                            Price = 999.0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 12,
                            Description = "PlayStation 5 console for next-gen gaming with ultra-high-speed SSD.",
                            ImageUrl = "/images/products/ps5_console.png",
                            Name = "PlayStation 5 Console",
                            Price = 499.99000000000001
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 7,
                            Description = "Classic low-top silhouette with leather overlays, padded collar comfort, and durable rubber traction for daily wear.",
                            ImageUrl = "/images/products/nike_dunk_cacao_pair.jpg",
                            Name = "Nike Dunk Low Retro - Cacao Wow",
                            Price = 129.99000000000001
                        });
                });

            modelBuilder.Entity("Web_Api_Amazon.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AccountType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CartItem", b =>
                {
                    b.HasOne("Web_Api_Amazon.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_Api_Amazon.Entities.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.HasOne("Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("CategoryProperty", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("CategoryProperties")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyDefinition", "PropertyDefinition")
                        .WithMany("CategoryProperties")
                        .HasForeignKey("PropertyDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("PropertyDefinition");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Web_Api_Amazon.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Web_Api_Amazon.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_Api_Amazon.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Web_Api_Amazon.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.HasOne("Web_Api_Amazon.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrderItem", b =>
                {
                    b.HasOne("Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_Api_Amazon.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductImage", b =>
                {
                    b.HasOne("Web_Api_Amazon.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductProperty", b =>
                {
                    b.HasOne("Web_Api_Amazon.Entities.Product", "Product")
                        .WithMany("Properties")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyDefinition", "PropertyDefinition")
                        .WithMany("ProductProperties")
                        .HasForeignKey("PropertyDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("PropertyDefinition");
                });

            modelBuilder.Entity("ProductVariant", b =>
                {
                    b.HasOne("Web_Api_Amazon.Entities.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductVariantValue", b =>
                {
                    b.HasOne("ProductVariant", "ProductVariant")
                        .WithMany("VariantValues")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyDefinition", "PropertyDefinition")
                        .WithMany()
                        .HasForeignKey("PropertyDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductVariant");

                    b.Navigation("PropertyDefinition");
                });

            modelBuilder.Entity("Web_Api_Amazon.Entities.Product", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Navigation("CategoryProperties");

                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ProductVariant", b =>
                {
                    b.Navigation("VariantValues");
                });

            modelBuilder.Entity("PropertyDefinition", b =>
                {
                    b.Navigation("CategoryProperties");

                    b.Navigation("ProductProperties");
                });

            modelBuilder.Entity("Web_Api_Amazon.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Images");

                    b.Navigation("OrderItems");

                    b.Navigation("Properties");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Web_Api_Amazon.Entities.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
