// <auto-generated />
using System;
using Amazon_clone.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    partial class ShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lifestyle"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Home"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Auto"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Health"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Clothing",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Shoes",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Computers / Laptops / Tablets",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "Mobile Phones",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "Audio and Wearables",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 11,
                            Name = "Cameras / Photo Equipment",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 12,
                            Name = "Gaming",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 13,
                            Name = "Home Decor",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 14,
                            Name = "Furniture",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 15,
                            Name = "Lighting",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 16,
                            Name = "Yard and Garden",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 17,
                            Name = "Tools / Hardware / Plumbing",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 18,
                            Name = "Building Materials",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 19,
                            Name = "Sports / Outdoor / Fitness",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 20,
                            Name = "Auto Parts / Accessories",
                            ParentCategoryId = 4
                        },
                        new
                        {
                            Id = 21,
                            Name = "Toys Kids",
                            ParentCategoryId = 5
                        },
                        new
                        {
                            Id = 22,
                            Name = "Books / Media",
                            ParentCategoryId = 5
                        },
                        new
                        {
                            Id = 23,
                            Name = "Health",
                            ParentCategoryId = 5
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 6,
                            Description = "Comfortable cotton t-shirt for everyday wear.",
                            ImageUrl = "/images/products/tshirt.jpg",
                            Name = "Men's Casual T-Shirt",
                            Price = 19.989999999999998
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 7,
                            Description = "Lightweight running shoes with breathable material.",
                            ImageUrl = "/images/products/sneakers.jpg",
                            Name = "Running Sneakers",
                            Price = 89.989999999999995
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 8,
                            Description = "13-inch laptop with Apple M2 chip and 16GB RAM.",
                            ImageUrl = "/images/products/macbook_air_m2.jpg",
                            Name = "Apple MacBook Air M2",
                            Price = 1499.99
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 9,
                            Description = "Flagship smartphone with advanced camera system.",
                            ImageUrl = "/images/products/galaxy_s24.jpg",
                            Name = "Samsung Galaxy S24",
                            Price = 999.99000000000001
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 10,
                            Description = "Noise-cancelling wireless headphones.",
                            ImageUrl = "/images/products/sony_xm5.jpg",
                            Name = "Sony WH-1000XM5",
                            Price = 399.99000000000001
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 11,
                            Description = "Mirrorless camera for photography enthusiasts.",
                            ImageUrl = "/images/products/canon_r10.jpg",
                            Name = "Canon EOS R10",
                            Price = 979.99000000000001
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 12,
                            Description = "Next-gen gaming console from Sony.",
                            ImageUrl = "/images/products/ps5.jpg",
                            Name = "PlayStation 5",
                            Price = 549.99000000000001
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 13,
                            Description = "Minimalist wall clock for home decor.",
                            ImageUrl = "/images/products/wall_clock.jpg",
                            Name = "Modern Wall Clock",
                            Price = 39.990000000000002
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 14,
                            Description = "Solid wood dining table for family meals.",
                            ImageUrl = "/images/products/dining_table.jpg",
                            Name = "Wooden Dining Table",
                            Price = 799.99000000000001
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 15,
                            Description = "Energy-efficient LED lamp with adjustable brightness.",
                            ImageUrl = "/images/products/desk_lamp.jpg",
                            Name = "LED Desk Lamp",
                            Price = 49.990000000000002
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 16,
                            Description = "Complete set of tools for gardening tasks.",
                            ImageUrl = "/images/products/garden_tools.jpg",
                            Name = "Garden Tool Set",
                            Price = 59.990000000000002
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 17,
                            Description = "Powerful electric drill for home improvement.",
                            ImageUrl = "/images/products/drill.jpg",
                            Name = "Electric Drill",
                            Price = 129.99000000000001
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 18,
                            Description = "High-quality concrete mix for construction.",
                            ImageUrl = "/images/products/concrete.jpg",
                            Name = "Concrete Mix",
                            Price = 14.99
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 19,
                            Description = "Adjustable dumbbell set for home workouts.",
                            ImageUrl = "/images/products/dumbbells.jpg",
                            Name = "Fitness Dumbbells Set",
                            Price = 119.98999999999999
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 20,
                            Description = "Universal phone holder for car dashboards.",
                            ImageUrl = "/images/products/car_holder.jpg",
                            Name = "Car Phone Holder",
                            Price = 24.989999999999998
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 21,
                            Description = "Educational toy set for kids.",
                            ImageUrl = "/images/products/blocks.jpg",
                            Name = "Kids Building Blocks",
                            Price = 34.990000000000002
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 22,
                            Description = "Comprehensive guide to C# and .NET development.",
                            ImageUrl = "/images/products/csharp_book.jpg",
                            Name = "C# Programming Book",
                            Price = 44.990000000000002
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 23,
                            Description = "Dietary supplement to support immunity.",
                            ImageUrl = "/images/products/vitamin_c.jpg",
                            Name = "Vitamin C Tablets",
                            Price = 14.99
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CartItem", b =>
                {
                    b.HasOne("Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.HasOne("Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrderItem", b =>
                {
                    b.HasOne("Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.HasOne("Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
